### PR TITLE
Update pi.jl

### PR DESCRIPTION
**Pull request by piotrek124-1**
As mentioned in https://github.com/JuliaBerry/PiGPIO.jl/issues/14

### CODE REVIEW

**Comment by Alexander-Barth** [comment]
@aviks @ViralBShah @simonbyrne
Can this PR be merged?
Thanks a lot!

**Comment by ViralBShah** [comment]
@piotrek124-1 @Alexander-Barth Please let me know if we should add you guys to have commit access to these repos.

**Comment by Alexander-Barth** [comment]
Thanks a lot for merging this PR.
Yes, I would like to have commit access. I use this repo for my lecture:

https://github.com/gher-uliege/drifter-raspberry-pi

I noticed some small formatting issues in the documentation that would be nice to address. There are also some GPIO functions implemented in python bot not in PiGPIO.jl  as far as I know (like `GPIO.add_event_detect`, https://sourceforge.net/p/raspberry-gpio-python/wiki/Inputs/) that I would probably need in future.

**Comment by ViralBShah** [comment]
@Alexander-Barth Invited you as an owner of the org.

**Comment by Alexander-Barth** [comment]
Thanks a lot @ViralBShah . I just accepted the invitation :-) 
For small changes, I usually do them directly in the repo. For larger changes, I will open a PR for discussion.
Would that work for you? 
(in any case, I am plot planning to break the API :-))

**Comment by ViralBShah** [comment]
Sounds great. You should feel comfortable merging PRs quickly and rapidly.

**Comment by Alexander-Barth** [comment]
Perfect !

**Pull request merged**
