### PR TITLE
General fixes for 1.0

### PR DESCRIPTION
**Pull request by Ellipse0934**
Removed StrPack and instead used `reinterpret` to get byte streams. The package is able to compile, some commands work now. 
TODO: Code refactoring and testing

### CODE REVIEW

**Comment by aviks** [comment]
Thanks for doing this @Ellipse0934 , appreciate it.

**Comment by Ellipse0934** [comment]
I have done some refactoring. Just broken down `pi.jl` into several manageable chunks. I intend to break them down even more as I continue to work on them.
Can you confirm that everything was working 0.6 ? I haven't properly investigated but some of the code seemed incorrect to me. Did you or anyone happen to test it ?

I think we ought to change the function names a bit for user friendliness. Thoughts ?

Do you plan to merge this now and I can continue working or do we merge once everything is done ?

**Comment by aviks** [comment]
Basic things were working in 0.6, get_value, set_value, set_pwm. But certainly not all functions were tested -- if it seems wrong, it's probably wrong. 

The code was ported from python : https://github.com/joan2937/pigpio/blob/master/pigpio.py

I think we should keep the low level interface as is, with similar names with python. And have a separate higher level layer. 

As for merging, whatever you are comfortable with.

**Comment by aviks** [comment]
If the basic functions are working, let's merge this, and continue working on master

**Pull request merged**
